title: "alexwlchan’s ideas for inclusive events"
email: "alex@alexwlchan.net"

author: "Alex Chan"
description: "Ideas for inclusive and accessible events"
url: "https://alexwlchan.net/ideas-for-inclusive-events"
github_repo: "https://github.com/alexwlchan/ideas-for-inclusive-events/"
twitter: "alexwlchan"

source: "src"
destination: "_site"

date_format: "%-d %B %Y"

permalink: "/:year/:month/:title/"

keep_files: ["images"]

markdown: "redcarpet"

redcarpet:
  extensions: ["smart", "with_toc_data"]

liquid:
  error_mode: "strict"
  strict_filters: true

sass:
  sass_dir: "_scss"
  style: "compressed"

collections:
  ideas:
    output: true
    permalink: "/ideas/:title/"
