title: "alexwlchan"
email: "alex@alexwlchan.net"

author: "Alex Chan"
description: "Ideas for inclusive and accessible events"
url: "https://alexwlchan.net/inclusive-events/"

source: "src"
destination: "_site"

date_format: "%-d %B %Y"

permalink: "/:year/:month/:title/"

keep_files: ["images"]

markdown: "redcarpet"

redcarpet:
  extensions: ["smart", "with_toc_data"]

liquid:
  error_mode: "strict"
  strict_filters: true

sass:
  sass_dir: "_scss"
  style: "compressed"
